spring:
  datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudTest
        username: root
        password: jan2016$

productCatalog:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8003
    ServerListRefreshInterval: 15000